/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "linked_list.h"
#include <stdio.h>
#include <stdlib.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void testListInit(void);
extern void testAppendSingleStackNode(void);
extern void testAppendSingleHeapNode(void);
extern void testAppendMultiHeapNode(void);
extern void testRemoveSingleStackNode(void);
extern void testRemoveMultiHeapNode(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("..\\\\TEST\\\\linked-list\\\\linked_list_test.c");
  run_test(testListInit, "testListInit", 21);
  run_test(testAppendSingleStackNode, "testAppendSingleStackNode", 27);
  run_test(testAppendSingleHeapNode, "testAppendSingleHeapNode", 40);
  run_test(testAppendMultiHeapNode, "testAppendMultiHeapNode", 56);
  run_test(testRemoveSingleStackNode, "testRemoveSingleStackNode", 79);
  run_test(testRemoveMultiHeapNode, "testRemoveMultiHeapNode", 90);

  return UnityEnd();
}
